### ISSUE TITLE
Scipy.stats import error: Library not loaded

### ISSUE THREAD

**Issue by dcbb** [The-Pineapple-Project/PineappleProject#1]
Upon `from scipy import stats` I get the following error:

ImportError: dlopen(/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so, 2): **Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib**
  Referenced from: /Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so
  Reason: image not found

May be related to #35, but I wanted to report it anyway. I just so much want to work with Pineapple.
Running Pineapple-Pro-0.7.4.

**Comment by dcbb** [comment]
Problem remains with version 0.8

**Comment by billmei** [comment]
You need the C headers for LibGFortran, try `$ sudo apt-get install libatlas-dev libatlas3gf-base`

**Comment by dcbb** [comment]
No `apt-get` on Mac, unfortunately, or am I missing something? 
I'm using `brew`, usually, but it does not know the packages you mention.

**Comment by billmei** [comment]
Ah! This is Pineapple Project, not Pineapple Pro, that's a different software project.
